* *DSV_COL_DELIM =,

* *DSV_TARGET_FILE =UsageTableFor2012ICSE.csv

/*
-- It seems that "Infer Generic Type" was never used so we special case it here
INSERT INTO "PUBLIC"."PER_REFACTORING_ID" 

("REFACTORING_ID", "CODINGTRACKER_PERFORMED_COUNT",
"CODINGTRACKER_UNDONE_COUNT", "CODINGTRACKER_REDONE_COUNT",
"CODINGSPECTATOR_PERFORMED_COUNT", "CODINGSPECTATOR_CANCELED_COUNT",
"CODINGSPECTATOR_UNAVAILABLE_COUNT", "INVOKED_BY_QUICKASSIST_COUNT",
"PREVIEW_COUNT",
"AVG_PERFORMED_OR_CANCELED_CONFIGURATION_DURATION_IN_MILLI_SEC")

VALUES ('org.eclipse.jdt.ui.change.type', 0, 0, 0, 0, 0, 0, 0, 0, 0);
*/

\.

SELECT

(SELECT "H"."HUMAN_READABLE_NAME"

FROM "PUBLIC"."REFACTORING_ID_TO_HUMAN_NAME" AS "H"

WHERE "H"."REFACTORING_ID" = "R"."REFACTORING_ID") AS "Automated_Refactoring",

"R"."CODINGTRACKER_PERFORMED_COUNT" AS "CT_Performed",

"R"."CODINGTRACKER_UNDONE_COUNT" AS "CT_Undo",

"CODINGTRACKER_REDONE_COUNT" AS "CT_Redo",

"R"."CODINGSPECTATOR_PERFORMED_COUNT" AS "CS_Performed",

"R"."CODINGSPECTATOR_CANCELED_COUNT" AS "CS_Canceled",

"R"."CODINGSPECTATOR_UNAVAILABLE_COUNT" AS "CS_Unavailable",

"R"."INVOKED_BY_QUICKASSIST_COUNT" AS "CS_Quick_Assist",

"R"."PREVIEW_COUNT" AS "CS_Preview",

"R"."AVG_PERFORMED_OR_CANCELED_CONFIGURATION_DURATION_IN_MILLI_SEC" AS
"CS_Average_Configuration_Time",

"A"."AVG_AFFECTED_LINES_FLOAT" AS "CT_Average_Affected_Lines",

"A"."AVG_AFFECTED_FILES_FLOAT" AS "CT_Average_Affected_Files",

"R"."P_UNDONE_GIVEN_PERFORMED" AS "P_Undo_Given_Performed",

"R"."P_CANCELED_GIVEN_CANCELED_OR_PERFORMED_WITHOUT_QA" AS
"P_Canceled_Given_Canceled_or_Performed_without_QA" ,

"R"."P_PERFORMED_GIVEN_WARNING_OR_ERROR_STATUS" AS
"P_Performed_Given_Warning_or_Error",

"R"."P_UNAVAILABLE_GIVEN_UNAVAILABLE_OR_CANCELED_OR_PERFORMED" AS
"P_Unavailable",

"R"."P_WARNING_GIVEN_PERFORMED_OR_CANCELED" AS "P_Warning",

"R"."P_ERROR_GIVEN_PERFORMED_OR_CANCELED" AS "P_Error",

"R"."P_FATAL_GIVEN_PERFORMED_OR_CANCELED" AS "P_Fatal_or_Error",

"R"."P_UNAVAILABLE_OR_WARNING_OR_ERROR_OR_FATAL_GIVEN_CS_REFACTORINGS" AS
"P_Unavailable_or_Warning_or_Error_or_Fatal_Error",

"R"."P_CANCELED_GIVEN_WARNING_OR_ERROR_OR_FATAL" AS
"P_Canceled_Given_Warning_or_Error_or_Fatal_Error"

FROM

"PUBLIC"."PER_REFACTORING_ID" "R" LEFT OUTER JOIN

(SELECT

"RCS"."REFACTORING_ID" AS "REFACTORING_ID",

COUNT("RCS"."USERNAME") AS "INVOCATION_COUNT",

CONVERT(AVG(CONVERT("RCS"."AFFECTED_FILES_COUNT", SQL_FLOAT)), NUMERIC(5, 2))
AS "AVG_AFFECTED_FILES_FLOAT",

CONVERT(AVG(CONVERT("RCS"."AFFECTED_LINES_COUNT", SQL_FLOAT)), NUMERIC(5, 2))
AS "AVG_AFFECTED_LINES_FLOAT",

SUM("RCS"."AFFECTED_FILES_COUNT") AS "SUM_AFFECTED_FILES",

SUM("RCS"."AFFECTED_LINES_COUNT") AS "SUM_AFFECTED_LINES"

FROM "PUBLIC"."JAVA_REFACTORING_CHANGE_SIZE" "RCS"

WHERE IS_JAVA_REFACTORING("RCS"."REFACTORING_ID")

GROUP BY "RCS"."REFACTORING_ID"

ORDER BY "RCS"."REFACTORING_ID") "A"

ON "R"."REFACTORING_ID" = "A"."REFACTORING_ID"

WHERE "R"."REFACTORING_ID" <> 'org.eclipse.jdt.ui.rename.java.project' AND
"R"."REFACTORING_ID" <> 'org.eclipse.jdt.ui.rename.source.folder';

.;

\xq :

