--This file is licensed under the University of Illinois/NCSA Open Source License. See LICENSE.TXT for details.

--This script generates a report of all refactoring events that reported a
--problem related to a name conflict.

--\i refactoring-message-analysis.sql

\c false

* USERNAME_MAX_LENGTH = 100

* HUMAN_READABLE_TIMESTAMP_MAX_LENGTH = 1000

DROP INDEX "TIMESTAMP_INDEX" IF EXISTS;

CREATE INDEX "TIMESTAMP_INDEX" ON "PUBLIC"."ALL_DATA" ("timestamp");

DROP TABLE "PUBLIC"."REFACTORING_MESSAGES_DUE_TO_NAME_CONFLICTS" IF EXISTS;

CREATE TABLE "PUBLIC"."REFACTORING_MESSAGES_DUE_TO_NAME_CONFLICTS" (
  "TIMESTAMP" BIGINT,
  "HUMAN_READABLE_TIMSTAMP" VARCHAR(*{HUMAN_READABLE_TIMESTAMP_MAX_LENGTH}),
  "USERNAME" VARCHAR(*{USERNAME_MAX_LENGTH}),
  "NUMBER_OF_AFFECTED_PARTICIPANTS" INT,
  "NUMBER_OF_PERFORMED" INT,
  "NUMBER_OF_CANCELED" INT
);

INSERT INTO "PUBLIC"."REFACTORING_MESSAGES_DUE_TO_NAME_CONFLICTS" (
  "TIMESTAMP",
  "HUMAN_READABLE_TIMSTAMP",
  "USERNAME",
  "NUMBER_OF_AFFECTED_PARTICIPANTS",
  "NUMBER_OF_PERFORMED",
  "NUMBER_OF_CANCELED"
)
SELECT
"T1"."TIMESTAMP" AS "TIMESTAMP",
(SELECT "human-readable timestamp" AS "HUMAN_READABLE_TIMSTAMP"
FROM "PUBLIC"."ALL_DATA" "T2"
WHERE "T2"."timestamp" = "TIMESTAMP"),
(SELECT "username" AS "USERNAME"
FROM "PUBLIC"."ALL_DATA" "T2"
WHERE "T2"."timestamp" = "TIMESTAMP"),
COUNT(DISTINCT("T1"."USERNAME")) AS "NUMBER_OF_AFFECTED_PARTICIPANTS",
COUNT(NULLIF("T1"."REACTION" <> 'PERFORMED', TRUE))/COUNT(*) AS
"NUMBER_OF_PERFORMED",
COUNT(NULLIF("T1"."REACTION" <> 'CANCELED' AND "T1"."REACTION" <> 'CANCELLED',
TRUE))/COUNT(*) AS "NUMBER_OF_CANCELED"
FROM "PUBLIC"."REFACTORING_MESSAGES" "T1"
WHERE "T1"."MESSAGE_PATTERN_ID" IN ('MP05' , 'MP29', 'MP77', 'MP39', 'MP78',
'MP45', 'MP33', 'MP34', 'MP35', 'MP37', 'MP40', 'MP87', 'MP48')
GROUP BY "TIMESTAMP", "USERNAME"
ORDER BY "TIMESTAMP", "USERNAME";

* *DSV_COL_DELIM=,
* *DSV_ROW_DELIM=\n
* *DSV_TARGET_FILE=RefactoringMessagesDueToNameConflicts.csv

\x SELECT * FROM "PUBLIC"."REFACTORING_MESSAGES_DUE_TO_NAME_CONFLICTS"

