--This file is licensed under the University of Illinois/NCSA Open Source License. See LICENSE.TXT for details.

--This script reports the number of time refactorings with specific properties (number of affected files and lines and configuration time) have been used.

/*

TODO: I don't know where the JavaRefactoringChangeSizeConfiguration.csv comes from.

DROP TABLE "PUBLIC"."REFACTORING_CHANGE_SIZE_CONFIGURATION_TIME" IF EXISTS;

CREATE TABLE "PUBLIC"."REFACTORING_CHANGE_SIZE_CONFIGURATION_TIME" (
  "REFACTORING_ID" VARCHAR(100),
  "CONFIGURATION_TIMESTAMP" BIGINT,
  "SIZE_TIMESTAMP" BIGINT,
  "AFFECTED_FILES_COUNT" INT,
  "AFFECTED_LINES_COUNT" INT,
  "CONFIGURATION_TIME_IN_MILLI_SEC" BIGINT
);

* *DSV_COL_SPLITTER = ,
* *DSV_TARGET_TABLE = "PUBLIC"."REFACTORING_CHANGE_SIZE_CONFIGURATION_TIME"

\m JavaRefactoringChangeSizeConfiguration.csv

DROP TABLE "PUBLIC"."CHANGE_SIZE_CONFIGURATION_TIME_MULTIPLICITIES" IF EXISTS;

CREATE TABLE "PUBLIC"."CHANGE_SIZE_CONFIGURATION_TIME_MULTIPLICITIES" (
  "AFFECTED_FILES_COUNT" INT,
  "AFFECTED_LINES_COUNT" INT,
  "CONFIGURATION_TIME_IN_SEC" BIGINT,
  "MULTIPLICITY" INT
);

INSERT INTO "PUBLIC"."CHANGE_SIZE_CONFIGURATION_TIME_MULTIPLICITIES" (
  "AFFECTED_FILES_COUNT",
  "AFFECTED_LINES_COUNT",
  "CONFIGURATION_TIME_IN_SEC",
  "MULTIPLICITY"
)
SELECT
"T"."AFFECTED_FILES_COUNT" AS "AFFECTED_FILES_COUNT",
"T"."AFFECTED_LINES_COUNT" AS "AFFECTED_LINES_COUNT",
"T"."CONFIGURATION_TIME_IN_MILLI_SEC" / 1000 AS "CONFIGURATION_TIME_IN_SEC",
COUNT(*) AS "MULTIPLICITY"
FROM "PUBLIC"."REFACTORING_CHANGE_SIZE_CONFIGURATION_TIME" "T"
GROUP BY "AFFECTED_FILES_COUNT", "AFFECTED_LINES_COUNT", "CONFIGURATION_TIME_IN_SEC";

* *DSV_COL_DELIM = ,
* *DSV_ROW_DELIM = \n
* *DSV_TARGET_FILE=JavaRefactoringChangeSizeConfigurationMultiplicities.csv

\x "PUBLIC"."CHANGE_SIZE_CONFIGURATION_TIME_MULTIPLICITIES"

*/

\p Extracting the size of Java refactorings

DROP TABLE "PUBLIC"."JAVA_REFACTORING_CHANGE_SIZE" IF EXISTS;

CREATE TABLE "PUBLIC"."JAVA_REFACTORING_CHANGE_SIZE" (
  "WORKSPACE_ID" VARCHAR(100),
  "TIMESTAMP" BIGINT,
  "REFACTORING_ID" VARCHAR(100),
  "AFFECTED_FILES_COUNT" INT,
  "AFFECTED_LINES_COUNT" INT
);

INSERT INTO "PUBLIC"."JAVA_REFACTORING_CHANGE_SIZE" (
  "WORKSPACE_ID",
  "TIMESTAMP",
  "REFACTORING_ID",
  "AFFECTED_FILES_COUNT",
  "AFFECTED_LINES_COUNT"
)
SELECT
"T"."WORKSPACE_ID" AS "WORKSPACE_ID",
"T"."TIMESTAMP" AS "TIMESTAMP",
JAVA_REFACTORING_ID("T"."REFACTORING_ID") AS "REFACTORING_ID",
"T"."AFFECTED_FILES_COUNT" AS "AFFECTED_FILES_COUNT",
"T"."AFFECTED_LINES_COUNT" AS "AFFECTED_LINES_COUNT"
FROM "PUBLIC"."REFACTORING_CHANGE_SIZE" "T"
WHERE IS_JAVA_REFACTORING("REFACTORING_ID");

* *DSV_COL_DELIM = ,
* *DSV_ROW_DELIM = \n
* *DSV_TARGET_FILE=JavaRefactoringChangeSize.csv

\x SELECT * FROM "PUBLIC"."JAVA_REFACTORING_CHANGE_SIZE"

\p Extracting the configuration time of Java refactorings

DROP TABLE "PUBLIC"."JAVA_REFACTORING_CONFIGURATION_TIME" IF EXISTS;

CREATE TABLE "PUBLIC"."JAVA_REFACTORING_CONFIGURATION_TIME" (
  "USERNAME" VARCHAR(100),
  "WORKSPACE_ID" VARCHAR(100),
  "TIMESTAMP" BIGINT,
  "REFACTORING_ID" VARCHAR(100),
  "CONFIGURATION_TIME_IN_MILLI_SEC" VARCHAR(100)
);

INSERT INTO "PUBLIC"."JAVA_REFACTORING_CONFIGURATION_TIME" (
  "USERNAME",
  "WORKSPACE_ID",
  "TIMESTAMP",
  "REFACTORING_ID",
  "CONFIGURATION_TIME_IN_MILLI_SEC"
)
SELECT
"T"."username" AS "USERNAME",
"T"."workspace ID" AS "WORKSPACE_ID",
"T"."timestamp" AS "TIMESTAMP",
JAVA_REFACTORING_ID("T"."id") AS "REFACTORING_ID",
"T"."navigation duration" AS "CONFIGURATION_TIME_IN_MILLI_SEC"
FROM "PUBLIC"."ALL_DATA" "T"
WHERE IS_JAVA_REFACTORING("T"."id") AND IS_CODINGSPECTATOR_PERFORMED("T"."recorder", "T"."refactoring kind") AND "T"."navigation duration" <> '';

* *DSV_COL_DELIM = ,
* *DSV_ROW_DELIM = \n
* *DSV_TARGET_FILE=JavaRefactoringConfigurationTime.csv

\x SELECT * FROM "PUBLIC"."JAVA_REFACTORING_CONFIGURATION_TIME"

* *DSV_COL_DELIM = ,
* *DSV_ROW_DELIM = \n
* *DSV_TARGET_FILE=ChangeSizePerRefactoringID.csv

\x SELECT "PUBLIC"."REFACTORING_CHANGE_SIZE"."REFACTORING_ID" AS "REFACTORING_ID", COUNT("PUBLIC"."REFACTORING_CHANGE_SIZE"."USERNAME") AS "INVOCATION_COUNT", AVG(CONVERT("PUBLIC"."REFACTORING_CHANGE_SIZE"."AFFECTED_FILES_COUNT",SQL_FLOAT)) AS "AVG_AFFECTED_FILES_FLOAT", AVG(CONVERT("PUBLIC"."REFACTORING_CHANGE_SIZE"."AFFECTED_LINES_COUNT",SQL_FLOAT)) AS "AVG_AFFECTED_LINES_FLOAT", AVG("PUBLIC"."REFACTORING_CHANGE_SIZE"."AFFECTED_FILES_COUNT") AS "AVG_AFFECTED_FILES_INT", AVG("PUBLIC"."REFACTORING_CHANGE_SIZE"."AFFECTED_LINES_COUNT") AS "AVG_AFFECTED_LINES_INT", SUM("PUBLIC"."REFACTORING_CHANGE_SIZE"."AFFECTED_FILES_COUNT") AS "SUM_AFFECTED_FILES", SUM("PUBLIC"."REFACTORING_CHANGE_SIZE"."AFFECTED_LINES_COUNT") AS "SUM_AFFECTED_LINES" FROM "PUBLIC"."REFACTORING_CHANGE_SIZE" WHERE IS_JAVA_REFACTORING("PUBLIC"."REFACTORING_CHANGE_SIZE"."REFACTORING_ID") GROUP BY "PUBLIC"."REFACTORING_CHANGE_SIZE"."REFACTORING_ID" ORDER BY "PUBLIC"."REFACTORING_CHANGE_SIZE"."REFACTORING_ID";

* *DSV_COL_DELIM = ,
* *DSV_ROW_DELIM = \n
* *DSV_TARGET_FILE=CountPerChangeSize.csv

\x SELECT "PUBLIC"."REFACTORING_CHANGE_SIZE"."AFFECTED_FILES_COUNT" AS "AFFECTED_FILES_COUNT", "PUBLIC"."REFACTORING_CHANGE_SIZE"."AFFECTED_LINES_COUNT" AS "L", COUNT(*) AS "MULTIPLICITY" FROM "PUBLIC"."REFACTORING_CHANGE_SIZE" WHERE IS_JAVA_REFACTORING("PUBLIC"."REFACTORING_CHANGE_SIZE"."REFACTORING_ID") GROUP BY "PUBLIC"."REFACTORING_CHANGE_SIZE"."AFFECTED_FILES_COUNT", "PUBLIC"."REFACTORING_CHANGE_SIZE"."AFFECTED_LINES_COUNT";

-- List the affected number of lines and files and configuration time of every refactoring.
-- Use the script refactoring-size-configuration-analysis.sql to combine the configuration data and refactoring size data

* *DSV_COL_DELIM = ,
* *DSV_ROW_DELIM = \n
* *DSV_TARGET_FILE=InvocationCountsPerRefactoringIDForChangeSize.csv

\x SELECT CASE "PUBLIC"."REFACTORING_CHANGE_SIZE"."REFACTORING_ID" WHEN 'org.eclipse.jdt.ui.rename.compilationunit' THEN  'org.eclipse.jdt.ui.rename.class' WHEN 'org.eclipse.jdt.ui.rename.type' THEN 'org.eclipse.jdt.ui.rename.class' ELSE "PUBLIC"."REFACTORING_CHANGE_SIZE"."REFACTORING_ID" END AS "REFACTORING_ID", COUNT(*) AS "C" FROM "PUBLIC"."REFACTORING_CHANGE_SIZE" WHERE IS_JAVA_REFACTORING("PUBLIC"."REFACTORING_CHANGE_SIZE"."REFACTORING_ID") GROUP BY CASE "PUBLIC"."REFACTORING_CHANGE_SIZE"."REFACTORING_ID" WHEN 'org.eclipse.jdt.ui.rename.compilationunit' THEN  'org.eclipse.jdt.ui.rename.class' WHEN 'org.eclipse.jdt.ui.rename.type' THEN 'org.eclipse.jdt.ui.rename.class' ELSE "PUBLIC"."REFACTORING_CHANGE_SIZE"."REFACTORING_ID" END ORDER BY CASE "PUBLIC"."REFACTORING_CHANGE_SIZE"."REFACTORING_ID" WHEN 'org.eclipse.jdt.ui.rename.compilationunit' THEN  'org.eclipse.jdt.ui.rename.class' WHEN 'org.eclipse.jdt.ui.rename.type' THEN 'org.eclipse.jdt.ui.rename.class' ELSE "PUBLIC"."REFACTORING_CHANGE_SIZE"."REFACTORING_ID" END;

