--This file is licensed under the University of Illinois/NCSA Open Source License. See LICENSE.TXT for details.

--This script reports the number of time refactorings with specific properties (number of affected files and lines and configuration time) have been used.

DROP TABLE "PUBLIC"."REFACTORING_CHANGE_SIZE_CONFIGURATION_TIME" IF EXISTS;

CREATE TABLE "PUBLIC"."REFACTORING_CHANGE_SIZE_CONFIGURATION_TIME" (
  "REFACTORING_ID" VARCHAR(100),
  "CONFIGURATION_TIMESTAMP" BIGINT,
  "SIZE_TIMESTAMP" BIGINT,
  "AFFECTED_FILES_COUNT" INT,
  "AFFECTED_LINES_COUNT" INT,
  "CONFIGURATION_TIME_IN_MILLI_SEC" BIGINT
);

* *DSV_COL_SPLITTER = ,
* *DSV_TARGET_TABLE = "PUBLIC"."REFACTORING_CHANGE_SIZE_CONFIGURATION_TIME"

\m JavaRefactoringChangeSizeConfiguration.csv

DROP TABLE "PUBLIC"."CHANGE_SIZE_CONFIGURATION_TIME_MULTIPLICITIES" IF EXISTS;

CREATE TABLE "PUBLIC"."CHANGE_SIZE_CONFIGURATION_TIME_MULTIPLICITIES" (
  "AFFECTED_FILES_COUNT" INT,
  "AFFECTED_LINES_COUNT" INT,
  "CONFIGURATION_TIME_IN_MILLI_SEC" BIGINT,
  "MULTIPLICITY" INT
);

INSERT INTO "PUBLIC"."CHANGE_SIZE_CONFIGURATION_TIME_MULTIPLICITIES" (
  "AFFECTED_FILES_COUNT",
  "AFFECTED_LINES_COUNT",
  "CONFIGURATION_TIME_IN_MILLI_SEC",
  "MULTIPLICITY"
)
SELECT
"T"."AFFECTED_FILES_COUNT" AS "AFFECTED_FILES_COUNT",
"T"."AFFECTED_LINES_COUNT" AS "AFFECTED_LINES_COUNT",
"T"."CONFIGURATION_TIME_IN_MILLI_SEC" / 1000 AS "CONFIGURATION_TIME_IN_SEC",
COUNT(*) AS "MULTIPLICITY"
FROM "PUBLIC"."REFACTORING_CHANGE_SIZE_CONFIGURATION_TIME" "T"
GROUP BY "AFFECTED_FILES_COUNT", "AFFECTED_LINES_COUNT", "CONFIGURATION_TIME_IN_SEC";

* *DSV_COL_DELIM = ,
* *DSV_ROW_DELIM = \n
* *DSV_TARGET_FILE=JavaRefactoringChangeSizeConfigurationMultiplicities.csv

\x "PUBLIC"."CHANGE_SIZE_CONFIGURATION_TIME_MULTIPLICITIES"

