--This file is licensed under the University of Illinois/NCSA Open Source License. See LICENSE.TXT for details.

--FIXEME: Remove the following and just rely on import-transaction-date.sql

\p Importing detailed-transactions.csv

DROP TABLE "PUBLIC"."DETAILED_TRANSACTIONS" IF EXISTS;

CREATE TABLE "PUBLIC"."DETAILED_TRANSACTIONS" (

  "TRANSACTION_IDENTIFIER" INT,

  "TRANSACTION_PATTERN_IDENTIFIER" INT,

  "USERNAME" VARCHAR(*{USERNAME_MAX_LENGTH}),

  "WORKSPACE_ID" VARCHAR(*{WORKSPACE_ID_MAX_LENGTH}),

  "CODINGSPECTATOR_VERSION" VARCHAR(*{CODINGSPECTATOR_VERSION_MAX_LENGTH}),

  "CODINGTRACKER_TIMESTAMP" BIGINT,

  "CODINGSPECTATOR_TIMESTAMP" BIGINT,

  "REFACTORING_ID" VARCHAR(*{REFACTORING_ID_MAX_LENGTH})

);

* *DSV_COL_SPLITTER =,

* *DSV_ROW_SPLITTER =\n

* *DSV_TARGET_TABLE ="PUBLIC"."DETAILED_TRANSACTIONS"

\m detailed-transactions.csv

\p Importing transaction-patterns.csv

DROP TABLE "PUBLIC"."TRANSACTION_PATTERNS" IF EXISTS;

CREATE TABLE "PUBLIC"."TRANSACTION_PATTERNS" (

  "TRANSACTION_PATTERN_IDENTIFIER" INT,

  "REFACTORING_ID" VARCHAR(*{REFACTORING_ID_MAX_LENGTH})

);

* *DSV_COL_SPLITTER =,

* *DSV_ROW_SPLITTER =\n

* *DSV_TARGET_TABLE ="PUBLIC"."TRANSACTION_PATTERNS"

\m transaction-patterns.csv

\p Computing the size and frequency of each transaction pattern

DROP TABLE "PUBLIC"."TRANSACTION_PATTERN_SUMMARIES" IF EXISTS;

CREATE TABLE "PUBLIC"."TRANSACTION_PATTERN_SUMMARIES" (

  "TRANSACTION_PATTERN_IDENTIFIER" INT,

  "SIZE" INT,

  "TRANSACTION_COUNT" INT

);

INSERT INTO "PUBLIC"."TRANSACTION_PATTERN_SUMMARIES" (

  "TRANSACTION_PATTERN_IDENTIFIER",

  "SIZE",

  "TRANSACTION_COUNT"

)

SELECT

"TRANSACTION_PATTERN_IDENTIFIER",

"SIZE",

"TRANSACTION_COUNT"

FROM

(SELECT

"DT"."TRANSACTION_PATTERN_IDENTIFIER" AS "TRANSACTION_PATTERN_IDENTIFIER",

(SELECT COUNT(*) FROM "PUBLIC"."TRANSACTION_PATTERNS" "TP" WHERE
"TP"."TRANSACTION_PATTERN_IDENTIFIER" = "DT"."TRANSACTION_PATTERN_IDENTIFIER")
AS "SIZE",

COUNT(DISTINCT "DT"."TRANSACTION_IDENTIFIER") AS "TRANSACTION_COUNT"

FROM "PUBLIC"."DETAILED_TRANSACTIONS" "DT"

GROUP BY "TRANSACTION_PATTERN_IDENTIFIER")

ORDER BY "TRANSACTION_COUNT" DESC, "SIZE" DESC,
"TRANSACTION_PATTERN_IDENTIFIER" ASC;

* *DSV_COL_DELIM =,

* *DSV_ROW_DELIM =\n

* *DSV_TARGET_FILE =transaction-pattern-summaries.csv

\x SELECT * FROM "PUBLIC"."TRANSACTION_PATTERN_SUMMARIES"

\p Oredring the transactions randomly

DROP TABLE "PUBLIC"."TRANSACTIONS_IN_RANDOM_ORDER" IF EXISTS;

CREATE TABLE "PUBLIC"."TRANSACTIONS_IN_RANDOM_ORDER" (

  "TRANSACTION_PATTERN_IDENTIFIER" INT,

  "TRANSACTION_IDENTIFIER" INT

);

INSERT INTO "PUBLIC"."TRANSACTIONS_IN_RANDOM_ORDER" (

  "TRANSACTION_PATTERN_IDENTIFIER",

  "TRANSACTION_IDENTIFIER"

)

SELECT

"TRANSACTION_PATTERN_IDENTIFIER",

"TRANSACTION_IDENTIFIER"

FROM "PUBLIC"."DETAILED_TRANSACTIONS" "DT"

GROUP BY "TRANSACTION_IDENTIFIER", "TRANSACTION_PATTERN_IDENTIFIER"

ORDER BY "TRANSACTION_PATTERN_IDENTIFIER", RAND();

* *DSV_COL_DELIM =,

* *DSV_ROW_DELIM =\n

* *DSV_TARGET_FILE =transactions-in-random-order.csv

\x SELECT * FROM "PUBLIC"."TRANSACTIONS_IN_RANDOM_ORDER"

