--This file is licensed under the University of Illinois/NCSA Open Source License. See LICENSE.TXT for details.

* USAGE_TIME_START =1305435601000 --May 15, 2011

* USAGE_TIME_STOP =1332619371000 -- February 3, 2011

\p Renaming columns of "PUBLIC"."ALL_DATA"

ALTER TABLE "PUBLIC"."ALL_DATA" ALTER COLUMN "username" RENAME TO "USERNAME";

ALTER TABLE "PUBLIC"."ALL_DATA" ALTER COLUMN "timestamp" RENAME TO "TIMESTAMP";

ALTER TABLE "PUBLIC"."ALL_DATA" ALTER COLUMN "id" RENAME TO "REFACTORING_ID";

ALTER TABLE "PUBLIC"."ALL_DATA" ALTER COLUMN "workspace ID" RENAME TO "WORKSPACE_ID";

ALTER TABLE "PUBLIC"."ALL_DATA" ALTER COLUMN "codingspectator version" RENAME
TO "CODINGSPECTATOR_VERSION";

ALTER TABLE "PUBLIC"."ALL_DATA" ALTER COLUMN "refactoring kind" RENAME TO
"REFACTORING_KIND";

ALTER TABLE "PUBLIC"."ALL_DATA" ALTER COLUMN "recorder" RENAME TO "RECORDER";

\p Deleting out-of-scope data from "PUBLIC"."ALL_DATA"

DELETE FROM "PUBLIC"."ALL_DATA" "AD"

WHERE NOT ("AD"."USERNAME" LIKE 'cs-___' AND *{USAGE_TIME_START} <
"AD"."TIMESTAMP" AND "AD"."TIMESTAMP" < *{USAGE_TIME_STOP} AND
IS_REFACTORING_ID_IN_ICSE2012_PAPER("AD"."REFACTORING_ID"));

\p Creating an index on "PUBLIC"."ALL_DATA"

DROP INDEX "ALL_DATA_INDEX" IF EXISTS;

CREATE INDEX "ALL_DATA_INDEX" ON "PUBLIC"."ALL_DATA" (

  "USERNAME",

  "WORKSPACE_ID",

  "CODINGSPECTATOR_VERSION",

  "TIMESTAMP",

  "RECORDER",

  "REFACTORING_KIND"

);

* USERNAME_MAX_LENGTH=100

* WORKSPACE_ID_MAX_LENGTH=100

* CODINGSPECTATOR_VERSION_MAX_LENGTH=100

* REFACTORING_ID_MAX_LENGTH=100

* HUMAN_READABLE_TIMESTAMP_MAX_LENGTH=100

* RECORDER_MAX_LENGTH=100

\p Importing matched-performed-refactorings.csv

DROP TABLE "PUBLIC"."MATCHED_PERFORMED_REFACTORINGS" IF EXISTS;

CREATE TABLE "PUBLIC"."MATCHED_PERFORMED_REFACTORINGS" (

  "CODINGSPECTATOR_HUMAN_READABLE_TIMESTAMP"
VARCHAR(*{HUMAN_READABLE_TIMESTAMP_MAX_LENGTH}),

  "CODINGSPECTATOR_TIMESTAMP" BIGINT,

  "CODINGSPECTATOR_VERSION" VARCHAR(*{CODINGSPECTATOR_VERSION_MAX_LENGTH}),

  "CODINGTRACKER_HUMAN_READABLE_TIMESTAMP"
VARCHAR(*{HUMAN_READABLE_TIMESTAMP_MAX_LENGTH}),

  "CODINGTRACKER_TIMESTAMP" BIGINT,

  "MISSING" VARCHAR(*{RECORDER_MAX_LENGTH}),

  "REFACTORING_ID" VARCHAR(*{REFACTORING_ID_MAX_LENGTH}),

  "USERNAME" VARCHAR(*{USERNAME_MAX_LENGTH}),

  "WORKSPACE_ID" VARCHAR(*{WORKSPACE_ID_MAX_LENGTH})

);

* *DSV_COL_SPLITTER =,

* *DSV_ROW_SPLITTER =\n

* *DSV_TARGET_TABLE ="PUBLIC"."MATCHED_PERFORMED_REFACTORINGS"

\m matched-performed-refactorings.csv

DELETE FROM "PUBLIC"."MATCHED_PERFORMED_REFACTORINGS" "MPR"

WHERE NOT ("MPR"."USERNAME" LIKE 'cs-___' AND *{USAGE_TIME_START} <
"MPR"."CODINGTRACKER_TIMESTAMP" AND "MPR"."CODINGTRACKER_TIMESTAMP" <
*{USAGE_TIME_STOP} AND
IS_REFACTORING_ID_IN_ICSE2012_PAPER("MPR"."REFACTORING_ID"));

\p Creating an index on "PUBLIC"."MATCHED_PERFORMED_REFACTORINGS"

DROP INDEX "MATCHED_PERFORMED_REFACTORINGS_INDEX" IF EXISTS;

CREATE INDEX "MATCHED_PERFORMED_REFACTORINGS_INDEX" ON
"PUBLIC"."MATCHED_PERFORMED_REFACTORINGS" (

  "USERNAME",

  "WORKSPACE_ID",

  "CODINGSPECTATOR_VERSION",

  "CODINGTRACKER_TIMESTAMP"

);

\p Exporting refactoring events under study

DROP TABLE "PUBLIC"."REFACTORINGS_UNDER_STUDY" IF EXISTS;

CREATE TABLE "PUBLIC"."REFACTORINGS_UNDER_STUDY" (

  "USERNAME" VARCHAR(*{USERNAME_MAX_LENGTH}),

  "WORKSPACE_ID" VARCHAR(*{WORKSPACE_ID_MAX_LENGTH}),

  "CODINGSPECTATOR_VERSION" VARCHAR(*{CODINGSPECTATOR_VERSION_MAX_LENGTH}),

  "CODINGTRACKER_TIMESTAMP" BIGINT,

  "CODINGSPECTATOR_TIMESTAMP" BIGINT,

  "REFACTORING_ID" VARCHAR(*{REFACTORING_ID_MAX_LENGTH})

);

INSERT INTO "PUBLIC"."REFACTORINGS_UNDER_STUDY" (

  "USERNAME",

  "WORKSPACE_ID",

  "CODINGSPECTATOR_VERSION",

  "CODINGTRACKER_TIMESTAMP",

  "CODINGSPECTATOR_TIMESTAMP",

  "REFACTORING_ID"

)

SELECT

"AD"."USERNAME" AS "USERNAME",

"AD"."WORKSPACE_ID" AS "WORKSPACE_ID",

"AD"."CODINGSPECTATOR_VERSION" AS "CODINGSPECTATOR_VERSION",

"AD"."TIMESTAMP" AS "CODINGTRACKER_TIMESTAMP",

(SELECT "MPR"."CODINGSPECTATOR_TIMESTAMP" FROM
"PUBLIC"."MATCHED_PERFORMED_REFACTORINGS" "MPR" WHERE "MPR"."USERNAME" =
"USERNAME" AND "MPR"."WORKSPACE_ID" = "AD"."WORKSPACE_ID" AND
"MPR"."CODINGSPECTATOR_VERSION" = "AD"."CODINGSPECTATOR_VERSION" AND
"MPR"."CODINGTRACKER_TIMESTAMP" = "AD"."TIMESTAMP") AS
"CODINGSPECTATOR_TIMESTAMP",

"AD"."REFACTORING_ID" AS "REFACTORING_ID"

FROM "PUBLIC"."ALL_DATA" "AD"

WHERE IS_CODINGTRACKER_PERFORMED("AD"."RECORDER", "AD"."REFACTORING_KIND")

ORDER BY "USERNAME", "WORKSPACE_ID", "CODINGSPECTATOR_VERSION",
"CODINGTRACKER_TIMESTAMP", "REFACTORING_ID";

* *DSV_COL_DELIM =,

* *DSV_ROW_DELIM =\n

* *DSV_TARGET_FILE =refactorings-under-study.csv

\x SELECT * FROM "PUBLIC"."REFACTORINGS_UNDER_STUDY"

