--This file is licensed under the University of Illinois/NCSA Open Source License. See LICENSE.TXT for details.

* USAGE_TIME_START =1305435601000 --May 15, 2011

* USAGE_TIME_STOP =1332619371000 -- February 3, 2011

\p Deleting out-of-scope data from ALL_DATA

DELETE FROM "PUBLIC"."ALL_DATA" "AD"

WHERE NOT ("AD"."username" LIKE 'cs-___' AND *{USAGE_TIME_START} <
"AD"."timestamp" AND "AD"."timestamp" < *{USAGE_TIME_STOP} AND
IS_REFACTORING_ID_IN_ICSE2012_PAPER("AD"."id"));

\p Creating an index on ALL_DATA

DROP INDEX "EVENT_LOCATOR_INDEX" IF EXISTS;

CREATE INDEX "EVENT_LOCATOR_INDEX" ON "PUBLIC"."ALL_DATA" (

  "username",

  "workspace ID",

  "codingspectator version",

  "timestamp",

  "recorder",

  "refactoring kind"

);

* USERNAME_MAX_LENGTH=100

* WORKSPACE_ID_MAX_LENGTH=100

* CODINGSPECTATOR_VERSION_ID_MAX_LENGTH=100

* REFACTORING_ID_MAX_LENGTH=100

DROP TABLE "PUBLIC"."REFACTORINGS_UNDER_STUDY" IF EXISTS;

CREATE TABLE "PUBLIC"."REFACTORINGS_UNDER_STUDY" (

  "USERNAME" VARCHAR(*{USERNAME_MAX_LENGTH}),

  "WORKSPACE_ID" VARCHAR(*{WORKSPACE_ID_MAX_LENGTH}),

  "CODINGSPECTATOR_VERSION" VARCHAR(*{CODINGSPECTATOR_VERSION_ID_MAX_LENGTH}),

  "TIMESTAMP" BIGINT,

  "REFACTORING_ID" VARCHAR(*{REFACTORING_ID_MAX_LENGTH})

);

INSERT INTO "PUBLIC"."REFACTORINGS_UNDER_STUDY" (

  "USERNAME",

  "WORKSPACE_ID",

  "CODINGSPECTATOR_VERSION",

  "TIMESTAMP",

  "REFACTORING_ID"

)

SELECT

"AD"."username" AS "USERNAME",

"AD"."workspace ID" AS "WORKSPACE_ID",

"AD"."codingspectator version" AS "CODINGSPECTATOR_VERSION",

"AD"."timestamp" AS "TIMESTAMP",

"AD"."id" AS "REFACTORING_ID"

FROM "PUBLIC"."ALL_DATA" "AD"

WHERE IS_CODINGTRACKER_PERFORMED("AD"."recorder", "AD"."refactoring kind")

ORDER BY "USERNAME", "WORKSPACE_ID", "CODINGSPECTATOR_VERSION", "TIMESTAMP",
"REFACTORING_ID";

* *DSV_COL_DELIM =,

* *DSV_ROW_DELIM =\n

* *DSV_TARGET_FILE =refactorings-under-study.csv

\x SELECT * FROM "PUBLIC"."REFACTORINGS_UNDER_STUDY"


