--This file is licensed under the University of Illinois/NCSA Open Source License. See LICENSE.TXT for details.

* USERNAME_MAX_LENGTH =100

* WORKSPACE_ID_MAX_LENGTH =100

* CODINGSPECTATOR_VERSION_MAX_LENGTH =100

* REFACTORING_ID_MAX_LENGTH =100

* HUMAN_READABLE_TIMESTAMP_MAX_LENGTH =100

* RECORDER_MAX_LENGTH =100

* TIMESTAMP_MAX_LENGTH =50

* CAPTURED_BY_CODINGSPECTATOR_MAX_LENGTH =50

* REFACTORING_KIND_MAX_LENGTH =50

* CODE_SNIPPET_WITH_SELECTION_MARKERS_MAX_LENGTH =1000000

* CODINGTRACKER_DESCRIPTION_MAX_LENGTH =1000

* COMMENT_MAX_LENGTH =10000

* DESCRIPTION_MAX_LENGTH =10000

* STATUS_MAX_LENGTH =100000

* INVOKED_BY_QUICKASSIST_MAX_LENGTH =50

* INVOKED_THROUGH_STRUCTURED_SELECTION_MAX_LENGTH =50

* NAVIGATION_DURATION_MAX_LENGTH =1000

* NAVIGATION_HISTORY_MAX_LENGTH =10000

* EXAMINER_MAX_LENGTH =10

* IS_COMPOSITE_REFACTORING_MAX_LENGTH =10

* TRANSACTION_DESCRIPTION_MAX_LENGTH =10000

